# Generated by Django 3.1 on 2020-08-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Newfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=10)),
                ('self', models.CharField(max_length=10)),
                ('fans', models.CharField(max_length=10)),
                ('greeting', models.CharField(max_length=30)),
                ('question', models.CharField(max_length=20)),
                ('praise', models.CharField(max_length=10)),
                ('tucao', models.CharField(max_length=10)),
                ('koupi1', models.CharField(max_length=10)),
                ('koupi2', models.CharField(max_length=10)),
                ('next', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=30)),
            ],
        ),
    ]
