# Generated by Django 3.1 on 2020-09-21 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('content', models.TextField(default='请添加内容', verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '文案模版',
            },
        ),
        migrations.CreateModel(
            name='PartTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30, verbose_name='用户名')),
                ('passowrd', models.CharField(max_length=20, verbose_name='密码')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name_plural': '兼职人员',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='编号')),
                ('series', models.CharField(max_length=10, verbose_name='系列')),
                ('self', models.CharField(max_length=10, verbose_name='自称')),
                ('fans', models.CharField(max_length=10, verbose_name='粉丝')),
                ('greeting', models.CharField(max_length=30, verbose_name='打招呼')),
                ('question', models.CharField(max_length=20, verbose_name='提问')),
                ('praise', models.CharField(max_length=10, verbose_name='称赞')),
                ('tucao', models.CharField(max_length=10, verbose_name='吐槽')),
                ('koupi1', models.CharField(max_length=10, verbose_name='口癖1')),
                ('koupi2', models.CharField(max_length=10, verbose_name='口癖2')),
                ('next', models.CharField(max_length=20, verbose_name='下集预告')),
                ('end', models.CharField(max_length=30, verbose_name='关注点赞')),
            ],
            options={
                'verbose_name_plural': '人设模版',
            },
        ),
        migrations.CreateModel(
            name='UploadList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdata', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('parttimer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.parttimer', verbose_name='兼职ID')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.profile', verbose_name='人设')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='请添加内容', verbose_name='内容')),
                ('status', models.BooleanField(choices=[(0, '通过'), (1, '不通过')], null=True, verbose_name='状态')),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.file', verbose_name='文案模版')),
                ('upload_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.uploadlist', verbose_name='上传ID')),
            ],
            options={
                'verbose_name_plural': '上传内容',
            },
        ),
        migrations.CreateModel(
            name='Newfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('content', models.TextField(default='请添加内容', verbose_name='内容')),
                ('status', models.BooleanField(choices=[(0, '通过'), (1, '不通过')], null=True, verbose_name='状态')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.profile', verbose_name='人设')),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.file', verbose_name='文案模版')),
            ],
            options={
                'verbose_name_plural': '新文案',
            },
        ),
    ]
