# Generated by Django 3.1 on 2020-08-20 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfile',
            name='content',
            field=models.TextField(default='请添加内容'),
        ),
        migrations.AddField(
            model_name='newfile',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='newfile',
            name='template_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DB.file'),
        ),
    ]
