# Generated by Django 3.1 on 2020-09-22 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadlist',
            options={'verbose_name_plural': '上传列表'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='koupi1',
            new_name='koupi',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='koupi2',
        ),
    ]
