# Generated by Django 3.1 on 2020-09-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_auto_20200922_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='koupi',
            field=models.CharField(max_length=10, verbose_name='口癖'),
        ),
    ]
