# Generated by Django 3.1 on 2020-08-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_auto_20200820_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content',
            field=models.TextField(default='请添加内容'),
        ),
    ]
