# Generated by Django 3.1 on 2020-09-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0003_auto_20200922_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='number',
            field=models.CharField(default='1', max_length=10, verbose_name='序号'),
        ),
    ]
