# Generated by Django 3.1 on 2020-08-20 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0004_auto_20200820_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfile',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DB.profile'),
        ),
    ]
