# Generated by Django 3.1.1 on 2020-09-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0005_auto_20200922_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlist',
            name='status',
            field=models.BooleanField(choices=[(0, '未审核'), (1, '审核')], null=True, verbose_name='状态'),
        ),
    ]
