# Generated by Django 3.1.1 on 2020-09-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0006_uploadlist_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parttimer',
            old_name='passowrd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='parttimer',
            old_name='account',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='uploadlist',
            name='status',
            field=models.BooleanField(choices=[(0, '未审核'), (1, '已审核')], null=True, verbose_name='状态'),
        ),
    ]
